ALTER TABLE shifts ADD COLUMN IF NOT EXISTS start_time TIME;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS end_time TIME;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS gender_required TEXT DEFAULT 'both';
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS number_required INTEGER DEFAULT 1;
